version: "3.8"
services:
  app:
    build: .
    container_name: mcp-semen
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
