name: Deploy mcp-semen
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy project to server
      - name: Write private key from base64
        run: |
          echo "${{ secrets.DEPLOY_KEY_B64 }}" | base64 -d > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key_path: /tmp/deploy_key
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/home/deploy/apps/mcp-semen"
          overwrite: true
          rm: true

      - name: Build & restart via docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key_path: /tmp/deploy_key
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd /home/deploy/apps/mcp-semen
            # если .env отсутствует — подтягиваем из секретов deploy
            [ -f .env ] || cp /home/deploy/secrets/mcp-semen.env .env
            docker compose down || true
            docker compose up -d --build
            docker image prune -f || true
