name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 207.154.216.202
          username: root
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/apps/mcp-semen
            docker-compose pull
            docker-compose up -d --build
